# From AWX Survey/Extra-Vars

# cluster_name
# cluster_provider
# cluster_regions
# cluster_spend_limit
# database_name
# user_name
# user_pass


- name: Cockroach Cloud
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:   
  - name: provision CC cluster
    fabiog1901.cockroachdb.cc_cluster:
      state: present
      name: "{{ cluster_name }}"
      provider: "{{ cluster_provider }}"
      plan: "{{ cluster_plan }}"
      regions: "{{ cluster_regions }}"
      request_unit_limit: "{{ request_unit_limit }}"
      storage_mib_limit: "{{ storage_mib_limit }}"

      api_client:
        api_version: '2023-04-10'
    register: out

  - name: create database
    fabiog1901.cockroachdb.cc_database:
      state: present
      cluster_id: "{{ out.cluster.id }}"
      name: "{{ database_name }}"
      api_client:
        api_version: '2022-09-20'

  - name: create user 
    fabiog1901.cockroachdb.cc_user:
      state: present
      cluster_id: "{{ out.cluster.id }}"
      name: "{{ user_name }}"
      password: "{{ user_pass }}"
      api_client:
        api_version: '2022-09-20'

  - debug:
      msg: "cockroach sql --url 'postgres://{{ user_name }}:{{ user_pass }}@{{ out.cluster.sql_dns }}:26257/{{ database_name }}?sslmode=verify-full' "
