##############
#   INFRA    #
##############

- name: UNPROVISION
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
    - config/cockroachdb.yaml
  tasks:     
    - name: destroy instances
      fabiog1901.cockroachdb.cloud_instance:
        state: absent
        deployment_id: "{{ deployment_id }}"
        deployment: {}
        defaults: {}

  tags:
    - cloud_instance
