apiVersion: v1
kind: Secret
metadata:
  name: fabio-postgres-configuration
  namespace: awx
stringData:
  host: host.minikube.internal
  port: '26257'
  database: awx
  username: ansible
  password: ansible
  sslmode: disable
  type: unmanaged
type: Opaque

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx1-demo
spec:
  service_type: nodeport
  # default nodeport_port is 30080
  nodeport_port: 30080
  postgres_configuration_secret: fabio-postgres-configuration
  